branches:
  only: 
    - master
matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.2     
      install:
        # 3rd party libraries
        - (cd dependency/setup && ./glm.sh)
        - (cd dependency/setup && ./libpng-ios.sh)
      script:
        - (cd libcat/proj && xcodebuild -project libcat.xcodeproj -target libcat-ios -sdk iphonesimulator11.2 build)
        - (cd example/ui_builtin/proj && xcodebuild -project example.xcodeproj -target example-ios -sdk iphonesimulator11.2 build)
  
    - language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-26.0.2
          - android-26
      before_install:
        # cmake agree license
        - mkdir -p ${ANDROID_HOME}/licenses/
        - echo -ne "\n8933bad161af4178b1185d1a37fbf41ea5269c55" >> ${ANDROID_HOME}/licenses/android-sdk-license
        - echo -ne "\n84831b9409646a918e30573bab4c9c91346d8abd\n504667f4c0de7af1a06de9f4b1727b84351f2910" >> ${ANDROID_HOME}/licenses/android-sdk-preview-license
        - yes | ${ANDROID_HOME}/tools/bin/sdkmanager 'cmake;3.6.4111459' > /dev/null
        # Install NDK
        - export ANDROID_NDK_VERSION=r15b
        - export ANDROID_NDK_HOME=/home/travis/build/shadow-paw/android-ndk/
        - if [ ! -f ${ANDROID_NDK_HOME}ndk-build ]; then curl -L http://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip -O; unzip -q android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip; mv android-ndk-${ANDROID_NDK_VERSION} ../android-ndk; fi
      install:
        # 3rd party libraries
        - (cd dependency/setup && ./glm.sh)
        - (cd dependency/setup && ./libpng-android.sh)
      script:
        - (cd libcat/proj && ${ANDROID_NDK_HOME}ndk-build -j4)
        - (cd example/ui_builtin/proj/android && ./gradlew assembleDebug)

notifications:
  email: false
