branches:
  only: 
    - master
matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode11.4
      cache:
        - cocoapods
      before_install:
        - gem install cocoapods -v 1.9.3
      script:
        - (cd libcat/proj && pod install && xcodebuild -workspace libcat.xcworkspace -scheme libcat-ios -sdk iphonesimulator13.4 build)
        - (cd example/ui_basic/proj && pod install && xcodebuild -workspace example.xcworkspace -scheme example-ios -sdk iphonesimulator13.4 build)
  
    - language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-26.0.2
          - android-26
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        timeout: 300
        directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - "$TRAVIS_BUILD_DIR/tools/android-ndk-r15b"
        - $HOME/vcpkg/
      before_install:
        # cmake agree license
        - mkdir -p ${ANDROID_HOME}/licenses/
        - echo -ne "\n8933bad161af4178b1185d1a37fbf41ea5269c55" >> ${ANDROID_HOME}/licenses/android-sdk-license
        - echo -ne "\n84831b9409646a918e30573bab4c9c91346d8abd\n504667f4c0de7af1a06de9f4b1727b84351f2910" >> ${ANDROID_HOME}/licenses/android-sdk-preview-license
        - yes | ${ANDROID_HOME}/tools/bin/sdkmanager 'cmake;3.6.4111459' > /dev/null
        # Install NDK
        - export ANDROID_NDK_VERSION=r15b
        - export ANDROID_NDK_HOME=/home/travis/build/shadow-paw/cat/tools/android-ndk-${ANDROID_NDK_VERSION}
        - if [ ! -f ${ANDROID_NDK_HOME}/ndk-build ]; then curl -L http://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip -O; mkdir -p tools; unzip -q -o android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip -d tools/; fi
      install:
        - export VCPKG_ROOT=${HOME}/vcpkg
        - git clone https://github.com/Microsoft/vcpkg.git ${VCPKG_ROOT}
        - ( cd ${VCPKG_ROOT} && ./bootstrap-vcpkg.sh && ./vcpkg integrate install )
        - ${VCPKG_ROOT}/vcpkg install glm zlib libpng libjpeg-turbo --triplet arm-android
        - ${VCPKG_ROOT}/vcpkg install glm zlib libpng libjpeg-turbo --triplet arm64-android
        - ${VCPKG_ROOT}/vcpkg install glm zlib libpng libjpeg-turbo --triplet x86-android
        - ${VCPKG_ROOT}/vcpkg install glm zlib libpng libjpeg-turbo --triplet x64-android
      script:
        - (cd libcat/proj && ${ANDROID_NDK_HOME}/ndk-build -j4)
        - (cd example/ui_basic/proj/android && ./gradlew assembleDebug)

notifications:
  email: false
