workspace 'libcat'

target 'libcat-mac' do
  platform :osx, '10.15'
  pod 'glm', '0.9.4.6'
  pod 'libpng', '1.6.35'
end

target 'libcat-ios' do
  platform :ios, '11'
  pod 'glm', '0.9.4.6'
  pod 'libpng', '1.6.35'
end
